"""
專案常數集中管理
"""

# Logger 名稱
LOGGER_NAME = "macos_video_auto_ocr_ass"

# 預設模型 repo 與檔名
DEFAULT_LLAMA_MODEL_REPO = "mradermacher/X-ALMA-13B-Group6-GGUF"
DEFAULT_LLAMA_MODEL_FILENAME = "X-ALMA-13B-Group6.Q8_0.gguf"
DEFAULT_MODEL_DIR = "models"

# 預設 context
DEFAULT_N_CTX = 2048
DEFAULT_N_THREADS = 4

# MarianMT pipeline 名稱
MARIANMT_PIPELINE = "translation"
# MarianMT magic number
MARIANMT_MAX_LENGTH = 512
MARIANMT_SPLIT_THRESHOLD = 450
MARIANMT_DEFAULT_SRC_LANG = "en"
MARIANMT_DEFAULT_TGT_LANG = "zh"
MARIANMT_DEFAULT_DEVICE = "mps"

# Video OCR magic number
VIDEO_OCR_DEFAULT_CHUNK_SIZE = 300.0
VIDEO_OCR_DEFAULT_DOWNSCALE_OBJC = 1

# Video heatmap magic number
HEATMAP_DEFAULT_GRID_INTERVAL = 300
HEATMAP_DEFAULT_CONTRAST_BOOST = 1.0
HEATMAP_DEFAULT_FONT_SIZE = 24
HEATMAP_GRID_COLOR = (100, 100, 100, 200)
HEATMAP_LABEL_BG_COLOR = (0, 0, 0, 180)
HEATMAP_LABEL_TEXT_COLOR = (255, 255, 255, 255)
HEATMAP_WHITE_BG_COLOR = (255, 255, 255, 255)
HEATMAP_GREEN_MULTIPLIER = 1.5
HEATMAP_ALPHA_MULTIPLIER = 0.8

# ASS 標籤正則
ASS_TAG_REGEX = r"{.*?}"
ASS_POS_REGEX = r"\\pos\(([+-]?\d+(?:\.\d+)?),([+-]?\d+(?:\.\d+)?)\)"

# 影片處理 magic number
DEFAULT_INTERVAL = 1.0
DEFAULT_DOWNSCALE = 2
DEFAULT_FONT_SIZE = 24

# 其他
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_TEMP_DIR = "temp"
